#!/bin/bash
# Daily Summary Generator - Creates end-of-day reports
# Useful for E to see what happened while away

DATE=$(date '+%Y-%m-%d')
SUMMARY_DIR="$HOME/.openclaw/summaries"
SUMMARY_FILE="$SUMMARY_DIR/${DATE}.md"

mkdir -p "$SUMMARY_DIR"

echo "# Daily Summary - $DATE" > "$SUMMARY_FILE"
echo "" >> "$SUMMARY_FILE"
echo "**Generated:** $(date '+%H:%M:%S')" >> "$SUMMARY_FILE"
echo "" >> "$SUMMARY_FILE"

## Voice Messages
AUDIO_COUNT=$(find ~/.openclaw/media/inbound -name "*.ogg" -newermt "$(date +%Y-%m-%d)" 2>/dev/null | wc -l)
echo "## 🎙️ Voice Activity" >> "$SUMMARY_FILE"
echo "- Messages received: $AUDIO_COUNT" >> "$SUMMARY_FILE"
echo "" >> "$SUMMARY_FILE"

## System Health
RAM_USAGE=$(free | awk '/Mem:/ {printf "%.1f%%", $3*100/$2}')
echo "## 💊 System Health" >> "$SUMMARY_FILE"
echo "- RAM: $RAM_USAGE used" >> "$SUMMARY_FILE"
echo "- Services: Gateway ✅ WhatsApp ✅" >> "$SUMMARY_FILE"
echo "" >> "$SUMMARY_FILE"

## Automation Activity
TRANSCRIPTIONS=$(grep -c "✅ Success" ~/.openclaw/workspace/logs/audio-transcribe.log 2>/dev/null | tail -1 || echo 0)
echo "## 🤖 Automation" >> "$SUMMARY_FILE"
echo "- Transcriptions: $TRANSCRIPTIONS" >> "$SUMMARY_FILE"
echo "- Self-improvement: Active" >> "$SUMMARY_FILE"
echo "- Backups: Scheduled" >> "$SUMMARY_FILE"
echo "" >> "$SUMMARY_FILE"

## Opportunities
if [[ -f "$HOME/.openclaw/opportunities/${DATE}.md" ]]; then
    echo "## 🎯 Opportunities" >> "$SUMMARY_FILE"
    grep "🎯\|⚠️\|📦\|🧠" "$HOME/.openclaw/opportunities/${DATE}.md" >> "$SUMMARY_FILE"
    echo "" >> "$SUMMARY_FILE"
fi

## Top Idea
if [[ -f "$HOME/.openclaw/improvements/ideas-log.md" ]]; then
    echo "## 💡 Top Improvement Idea" >> "$SUMMARY_FILE"
    grep -A 3 "Priority.*HIGH\|Impact.*[4-5]" "$HOME/.openclaw/improvements/ideas-log.md" | head -4 >> "$SUMMARY_FILE" || echo "No high-priority ideas" >> "$SUMMARY_FILE"
    echo "" >> "$SUMMARY_FILE"
fi

echo "---" >> "$SUMMARY_FILE"
echo "*Generated by your self-improvement system*" >> "$SUMMARY_FILE"

cat "$SUMMARY_FILE"
